### ISSUE TITLE
在服务端运行会调用渲染导致崩溃

### ISSUE THREAD

**Issue by gundami** [Phoupraw/CreateSDelightFabricJava#2]
如题，以下是报错
`[17:51:56] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createsdelight'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.13.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.13.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.loadClasses(MyModInitializer.java:10) ~[CreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.onInitialize(MyModInitializer.java:20) ~[CreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.13.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at phoupraw.mcmod.createsdelight.registry.MyFluids.<clinit>(MyFluids.java:6) ~[CreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.loadClasses(MyModInitializer.java:10) ~[CreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.onInitialize(MyModInitializer.java:20) ~[CreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.13.jar:?]
        ... 7 more`

**Comment by Phoupraw** [comment]
能上传完整的latest.log或者崩溃报告吗？
