### ISSUE TITLE
pre4版本似乎无法在服务端正常运行。The pre4 version does not seem to work properly on the server side.

### ISSUE THREAD

**Issue by LittleCircleOO** [Phoupraw/CreateSDelightFabricJava#3]
#### 版本
Minecraft 1.19.2
Fabric Loader 0.14.12
Create's Delight 0.1.0-pre3
#### 问题描述
在加入该模组后，服务端启动失败，报错如下：
```
[main/ERROR]: Failed to start the minecraft server 
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createsdelight'!      
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader
-0.14.12.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.12.j
ar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.12.
jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.12.j
ar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.12.jar:?]      
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-
loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]       
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader
-0.14.12.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.1]
Caused by: java.lang.ExceptionInInitializerError
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.loadClasses(MyModInitializer.java:10) ~[%5B机械动力乐
事%5DCreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.onInitialize(MyModInitializer.java:20) ~[%5B机械动力 
乐事%5DCreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.
jar:?]
        ... 8 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandl
er in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0
.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) 
~[fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415)
 ~[fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-load
er-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-
0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14
.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at phoupraw.mcmod.createsdelight.registry.MyFluids.<clinit>(MyFluids.java:6) ~[%5B机械动力乐事%5DCreateSDelightF
abricJava-0.1.0-pre3.jar:?]
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.loadClasses(MyModInitializer.java:10) ~[%5B机械动力乐
事%5DCreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at phoupraw.mcmod.createsdelight.registry.MyModInitializer.onInitialize(MyModInitializer.java:20) ~[%5B机械动力 
乐事%5DCreateSDelightFabricJava-0.1.0-pre3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.
jar:?]
        ... 8 more
```
附完整日志：
[latest.log](https://github.com/Phoupraw/CreateSDelightFabricJava/files/10610102/latest.log)

**Comment by LittleCircleOO** [comment]
与 #2 重复，已自行关闭

**Comment by LittleCircleOO** [comment]
经过测试，同样的问题在 pre4 中仍可复现，因此重新打开 issue。
#### 版本
Minecraft 1.19.2
Fabric Loader 0.14.12
Create's Delight 0.1.0-pre4
#### 错误日志
```
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createsdelight'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.12.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.1]
Caused by: java.lang.ExceptionInInitializerError
	at phoupraw.mcmod.createsdelight.registry.MyModInitializer.loadClasses(MyModInitializer.java:10) ~[%5B机械动力乐事%5DCreateSDelightFabricJava-0.1.0-pre4.jar:?]
	at phoupraw.mcmod.createsdelight.registry.MyModInitializer.onInitialize(MyModInitializer.java:21) ~[%5B机械动力乐事%5DCreateSDelightFabricJava-0.1.0-pre4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at phoupraw.mcmod.createsdelight.registry.MyItems.<clinit>(MyItems.java:108) ~[%5B机械动力乐事%5DCreateSDelightFabricJava-0.1.0-pre4.jar:?]
	at phoupraw.mcmod.createsdelight.registry.MyModInitializer.loadClasses(MyModInitializer.java:10) ~[%5B机械动力乐事%5DCreateSDelightFabricJava-0.1.0-pre4.jar:?]
	at phoupraw.mcmod.createsdelight.registry.MyModInitializer.onInitialize(MyModInitializer.java:21) ~[%5B机械动力乐事%5DCreateSDelightFabricJava-0.1.0-pre4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.jar:?]
	... 8 more
```
完整日志：
[2023-02-06-5.log](https://github.com/Phoupraw/CreateSDelightFabricJava/files/10670328/2023-02-06-5.log)
